### ISSUE TITLE
XFCE 4.12 Restart icon missing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Faenza-Fusion/faenza-fusion-icon-theme#15]
```
What steps will reproduce the problem?
1. Click 'menu'
2. Select Log Out option
3. Restart icon is missing :(

What is the expected output? What do you see instead?
- I see a default gnome restart icon.

What version of the product are you using? On what operating system?
- Arch Linux - XFCE 4.12

Please provide any additional information below.
- This affects Faenza and Faience icon theme.

```

Original issue reported on code.google.com by `renato...@gmail.com` on 16 Jun 2015 at 11:45

Attachments:
* [restart-missing.png](https://storage.googleapis.com/google-code-attachments/faenza-icon-theme/issue-15/comment-0/restart-missing.png)

**Comment by Kazhnuz** [comment]
Resolved by https://github.com/Faenza-Fusion/faenza-fusion-icon-theme/commit/e5225ec2526c1b717f2acc1a1a16cd13c71cefc1
