### ISSUE TITLE
Clementine player icon

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Faenza-Fusion/faenza-fusion-icon-theme#2]
```
The great Faenza icon theme misses the clementine player 
(http://code.google.com/p/clementine-player/) icon. I'm not a professional 
designer but I've did my best to draw one.

I would be happy to contribute my work to the Faenza (please see the 
attachment). Feel free to adjust my icon in any way if it's worth.
```

Original issue reported on code.google.com by `rudchen...@gmail.com` on 28 May 2011 at 9:28

Attachments:
* [clementine.svg](https://storage.googleapis.com/google-code-attachments/faenza-icon-theme/issue-2/comment-0/clementine.svg)

**Comment by Kazhnuz** [comment]
Clementine is already included, so I'll close that issue
